In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

# train-test-split

In [6]:

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_test

array([[ 8.47111806e-01, -6.91535834e-01,  9.81667707e-01, ...,
         2.17550250e+00,  2.03513164e+00,  1.22591657e+00],
       [-7.20435963e-02,  3.36759493e-01, -8.91843599e-02, ...,
        -7.04682303e-01, -1.06104415e+00,  6.29270889e-02],
       [-4.45889677e-01, -7.10666910e-01, -4.37017361e-01, ...,
        -4.62904259e-01,  4.82783737e-01, -4.65906070e-01],
       ...,
       [-5.38648479e-01, -1.24394565e+00, -5.37856270e-01, ...,
        -3.50352411e-01, -3.31730311e-01,  2.46965463e-01],
       [-1.78856762e-01,  7.19381010e-01, -2.05945203e-01, ...,
         2.17810552e-01, -1.15347982e-03, -8.10146523e-01],
       [-2.00845386e+00, -1.40177702e+00, -1.96633945e+00, ...,
        -1.76149629e+00,  1.02790782e-01,  5.56282971e-01]])

In [9]:
y_train

405    B
487    M
171    M
262    M
6      M
      ..
495    B
251    B
345    B
442    B
35     M
Name: diagnosis, Length: 455, dtype: object

# label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

# Numpy arrays to Pytorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[1]

(tensor([ 1.4936, -0.1128,  1.4757,  1.4354,  0.9350,  0.7976,  1.8125,  1.8663,
          0.0787, -0.2319,  0.5699,  0.3586,  0.3559,  0.5765, -0.5894,  0.1705,
          0.4195, -0.0176, -0.3869, -0.2274,  1.5788,  0.7818,  1.3726,  1.4887,
          0.8504,  0.7579,  1.5441,  1.4190,  0.6719,  0.3495]),
 tensor(1.))

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# Define the model

In [19]:
import torch.nn as nn

class MysimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# important parameters

In [20]:
learning_rate = 0.1
epochs = 25

In [21]:
# create model
model = MysimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss fuction
loss_function = nn.BCELoss()

# Training Pipeline

In [29]:
# define loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    # forward pass
    y_pred = model(batch_features)
    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))
    # clear gradients
    optimizer.zero_grad()
    # backward pass
    loss.backward()
    # parameters update
    optimizer.step()

    # print loss in each epoch


  print(f'Epoch: {epoch + 1}, Loss:{loss.item()}')

Epoch: 1, Loss:0.028384294360876083
Epoch: 2, Loss:0.003217600053176284
Epoch: 3, Loss:0.02944904938340187
Epoch: 4, Loss:0.01954108290374279
Epoch: 5, Loss:0.01378194335848093
Epoch: 6, Loss:0.0010241472627967596
Epoch: 7, Loss:0.07398875057697296
Epoch: 8, Loss:0.010365985333919525
Epoch: 9, Loss:0.003338068723678589
Epoch: 10, Loss:0.07806093990802765
Epoch: 11, Loss:0.16439148783683777
Epoch: 12, Loss:0.022767821326851845
Epoch: 13, Loss:0.032872218638658524
Epoch: 14, Loss:0.03232376649975777
Epoch: 15, Loss:0.015239973552525043
Epoch: 16, Loss:0.004533691797405481
Epoch: 17, Loss:0.29898443818092346
Epoch: 18, Loss:0.0019738737028092146
Epoch: 19, Loss:0.0040911659598350525
Epoch: 20, Loss:0.04323232173919678
Epoch: 21, Loss:0.05435711890459061
Epoch: 22, Loss:0.007210985757410526
Epoch: 23, Loss:0.006783843506127596
Epoch: 24, Loss:0.010343515314161777
Epoch: 25, Loss:0.01393574196845293

# Evalution

In [30]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9488